### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by ddbuscombe** [2320sharon/PythonWLDtoCSV#5]
here's a test dataset (filtered.zip) that currently gives me the following output

```sh
(base) marda@pop-os:/Projects/PythonWLDtoCSV$ python gui.py 

Log files location: /Projects/PythonWLDtoCSV/log_files

Log: /Projects/PythonWLDtoCSV/log_files/log_02-Nov-2021_21_49_12.log has been created. 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/marda/anaconda3/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "gui.py", line 130, in <lambda>
    self.Open_Folder_button = tk.Button(self.folder_frame, text="Select Folder", command= lambda: self.OpenFileDialog(True),background=MainApp.button_purple,fg="white")
  File "gui.py", line 394, in OpenFileDialog
    self.populateFilesList(filePath)
  File "gui.py", line 350, in populateFilesList
    validFilesList=self.createValidFilesList(filesList)
  File "gui.py", line 329, in createValidFilesList
    currentFileTypes.remove(extension)
ValueError: list.remove(x): x not in list
```

not sure why 

[log_02-Nov-2021_21_49_12.log](https://github.com/2320sharon/PythonWLDtoCSV/files/7465399/log_02-Nov-2021_21_49_12.log)

[filtered.zip](https://github.com/2320sharon/PythonWLDtoCSV/files/7465401/filtered.zip)

**Comment by dbuscombe-usgs** [comment]
still getting this error ... can you please take a look? thanks

**Comment by dbuscombe-usgs** [comment]
my log file (not informative
[log_09-Nov-2021_19_15_33.log](https://github.com/2320sharon/PythonWLDtoCSV/files/7509557/log_09-Nov-2021_19_15_33.log)
)

this is frustrating for me because it is likely a very simple fix, but the program is over-engineered. It is therefore very hard to debug. we don't need all the error checking - please, make your programs simpler and more robust to inputs

**Comment by dbuscombe-usgs** [comment]
The problem is because the files have periods in the name, so the logic based around `fileName,extension = file.split(".",1)` wont work . Therefore `createValidFilesList` needs to be re-implemented. thank you!

**Comment by dbuscombe-usgs** [comment]
[chunk1_2018121.zip](https://github.com/2320sharon/PythonWLDtoCSV/files/7509615/chunk1_2018121.zip)
 here's another test set

**Comment by 2320sharon** [comment]
Working on this now. I will post updates as I go.

**Comment by 2320sharon** [comment]
> my log file (not informative [log_09-Nov-2021_19_15_33.log](https://github.com/2320sharon/PythonWLDtoCSV/files/7509557/log_09-Nov-2021_19_15_33.log) )
> 
> we don't need all the error checking, really - the error messages dont even tell me what the problem is

I'll work on making the error message more informative in future updates.

**Comment by 2320sharon** [comment]
> The problem is because the files have periods in the name, so the logic based around `fileName,extension = file.split(".",1)` wont work . Therefore `createValidFilesList` needs to be re-implemented. thank you!

Ah I made things too complicated by using file.split(".",1) when I should have used os.path.splitext(f"{file}"), which works for all os's and works with files with periods in it. Thank you for catching this bug!

This bug also impacted how files were being compared but I think I have finalized the fix and will be posting soon.
